# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-14 · Project: wm-dashboard-fussball-wahrscheinlichkeit
"""Regressionstests fuer die in Phase 3 bestaetigten Bugs (BUG-001..006).

Jeder Test prueft den BEABSICHTIGTEN Vertrag (REQ) und schlaegt daher auf dem aktuellen
Code fehl -> als xfail(strict=True) markiert (Report: XFAIL). Nach Anwenden des jeweiligen
Fix-Patches muss der Test bestehen; strict=True macht ein versehentliches Bestehen sichtbar
(XPASS -> Fehler -> Marker entfernen). Import wie tests/test_model.py.
"""
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def test_bug001_simulate_small_runs_does_not_crash():
    """REQ-001: simulate muss fuer beliebige runs>=1 normiert zurueckkehren, nicht crashen."""
    from src.model import monte_carlo
    mc = monte_carlo.simulate(1.3, 1.3, runs=50, seed=1)
    # Probs sind auf 4 Nachkommastellen gerundet -> Toleranz entsprechend
    assert abs(sum(mc["probs"].values()) - 1.0) < 1e-3


def test_bug002_uncertainty_band_invariant_to_runs():
    """REQ-002: Bandbreite muss ~invariant gegen MC_RUNS sein (Parameter-Unsicherheit)."""
    from src.model import monte_carlo
    def width(r):
        b = monte_carlo.simulate(1.6, 1.0, runs=r, seed=1, rho=0.0)["uncertainty"]["team1_win"]
        return b["p95"] - b["p05"]
    w_lo, w_hi = width(20000), width(200000)
    assert abs(w_lo - w_hi) < 0.03, f"Band schrumpft mit runs: {w_lo:.4f} -> {w_hi:.4f}"


def test_bug003_blend_lambdas_uses_books_when_market_absent():
    """REQ-003: fehlt Polymarket, muss blend_lambdas die Buecher-Torstruktur nutzen (wie blend_probs)."""
    from src.model import ensemble
    books = {"probs": {"team1_win": 0.60, "draw": 0.25, "team2_win": 0.15}}
    model = {"probs": {"team1_win": 0.40, "draw": 0.30, "team2_win": 0.30},
             "lambda1": 1.30, "lambda2": 1.30}
    blend = ensemble.blend_probs(None, model, None, books=books)
    lams = ensemble.blend_lambdas(None, model, blend.get("weights_used", {}), books=books)
    # Buecher implizieren lam1>lam2; korrekte Mischung muss von der reinen Modell-1.30/1.30 abweichen
    assert abs(lams["lambda1"] - 1.30) > 0.02, f"lambda ignoriert Buecher: {lams}"


def test_bug004_integer_total_line_respects_push():
    """REQ-004: bei Linie 3.0 muss p_under = P(total<=2) sein, nicht 1 - P(total>=4)."""
    from src.model import monte_carlo, value_betting
    mc = monte_carlo.simulate(1.4, 1.2, runs=40000, seed=3)
    match = {"team1": "A", "team2": "B",
             "ensemble": {"probs": mc["probs"]}, "monte_carlo": mc, "model": {}}
    slot = {"best_odds": 2.0, "book": "bk", "consensus_prob": 0.5, "n_books": 10}
    best = {"h2h": {}, "n_bookmakers": 10, "books": ["bk"],
            "totals": {"3.0": {"over": dict(slot), "under": dict(slot)}}}
    out = value_betting.evaluate_match(match, best)
    under = next(r for r in out["rows"] if r["selection"].startswith("Under"))
    td = mc["total_goals_dist"]
    expected = round(sum(td[:3]), 4)  # P(total<=2)
    assert abs(under["p_model"] - expected) < 0.02, f"Push leakt: {under['p_model']} != {expected}"


def test_bug005_totals_sigma_not_smaller_than_1x2():
    """REQ-005: ein Markt ohne MC-Band darf bei gleichem Edge kein kleineres sigma bekommen."""
    from src.model import value_betting as vb
    r_1x2 = vb._row("1X2", "s", 3.0, "bk", 0.55, 0.50, band_width=0.18, n_books=20)
    r_tot = vb._row("Über/Unter", "s", 3.0, "bk", 0.55, 0.50, band_width=None, n_books=20)
    assert r_tot["sigma"] >= r_1x2["sigma"] - 1e-9, (r_tot["sigma"], r_1x2["sigma"])


def test_bug006_whale_exposure_is_usd_commensurable(monkeypatch):
    """REQ-006: Holder-Exposure muss in USD (amount*Preis) zaehlen, nicht roh als Anteilszahl."""
    from src.model import whale_scoring
    from src.data_sources import polymarket_client as pm
    monkeypatch.setattr(pm, "get_user_activity", lambda *a, **k: [])
    monkeypatch.setattr(whale_scoring.time, "sleep", lambda *a, **k: None)
    # Markt: Yes-Preis fuer team1_win = 0.50
    snap = {"market": {"raw": {"team1_win": 0.50, "draw": 0.30, "team2_win": 0.20},
                       "probs": {"team1_win": 0.5, "draw": 0.3, "team2_win": 0.2}},
            "holders": {"team1_win": [{"proxyWallet": "0xH", "amount": 800}]},
            "trades": {}}
    sig = whale_scoring.whale_signal(snap)
    expo = sig["wallets"][0]["exposure"]["team1_win"]
    # 800 Anteile @ 0.50 = $400 USD-Exposure (kommensurabel mit Trade-USD); Code zaehlt roh 800
    assert abs(expo - 400.0) < 1.0, f"Holder-Anteile nicht in USD bewertet: {expo}"


def test_bug007_whale_default_matches_config():
    """REQ-009: Inline-Default fuer whale-Gewicht muss config.ENSEMBLE_WEIGHTS entsprechen."""
    import inspect
    from src.model import ensemble
    src = inspect.getsource(ensemble.blend_probs)
    # Fix: kein hartkodiertes Literal mehr, sondern config-Default
    assert 'weights.get("whale", 0.2)' not in src, "hartkodierter 0.2-Default noch vorhanden"
    assert 'ENSEMBLE_WEIGHTS["whale"]' in src, "config-Default nicht referenziert"


def test_bug008_market_agreement_considers_all_outcomes():
    """REQ-008: Uneinigkeit bei draw/away muss den Agreement-Faktor senken."""
    from src.model import data_quality
    match = {"market": {"probs": {"team1_win": 0.50, "draw": 0.45, "team2_win": 0.05}},
             "books":  {"probs": {"team1_win": 0.50, "draw": 0.05, "team2_win": 0.45}}}
    f, _ = data_quality._market_agreement(match)
    assert f < 0.9, f"Agreement ignoriert draw/away-Dispersion: {f}"


def test_bug009_closing_loop_ranks_perfect_rps_first():
    """Learning-Loop: Bestenliste muss nach mean_rps sortieren; RPS==0.0 darf nicht
    als falsy auf den Brier zurueckfallen (sonst landet die perfekte Quelle zu weit hinten)."""
    from src.model.closing_loop import generate_report
    calib = {"status": "live",
             "matches": [{"slug": "m1", "result": "1:0", "outcome": "team1_win",
                          "brier": {"market": 0.2}}],
             "summary": {
                 "perfectsrc": {"mean_rps": 0.0, "mean_brier": 0.40, "mean_log_loss": 0.1,
                                "hit_rate": 1.0, "n": 3},
                 "oksrc": {"mean_rps": 0.10, "mean_brier": 0.20, "mean_log_loss": 0.3,
                           "hit_rate": 0.5, "n": 3}},
             "betting": {}}
    report = generate_report(calib, "2026-06-14T10:00:00")
    assert report.index("perfectsrc") < report.index("oksrc"), \
        "RPS 0.0 wurde falsy-bedingt nach hinten sortiert"


def test_req007_distinct_known_teams_never_substring_match(monkeypatch):
    """REQ-007 (Haertung): zwei VERSCHIEDENE bekannte Teams duerfen sich nie per
    Teilzeichenkette treffen; un-kanonisierte Varianten matchen weiterhin per Substring."""
    from src import config
    from src.model.calibration import _team_eq
    # Synthetisches kollidierendes Paar als 'bekannt' einspielen
    monkeypatch.setattr(config, "known_team_names_lower",
                        lambda: {"guinea", "equatorial guinea"})
    assert _team_eq("Guinea", "Equatorial Guinea") is False      # beide bekannt -> kein Substring
    assert _team_eq("Guinea", "Guinea") is True                  # gleich
    # un-kanonisierte Variante (nicht in 'known') darf weiter per Substring greifen
    assert _team_eq("Korea", "Korea Republic XYZ") is True


def test_req007_real_field_has_no_collisions():
    """REQ-007: im aktuellen 48er-Feld matcht kein Paar verschiedener Teams."""
    from src import config
    from src.model.calibration import _team_eq
    names = sorted(config.known_team_names_lower())
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            assert not _team_eq(a, b), f"Falschtreffer: {a} ~ {b}"


def test_req011_extract_1x2_handles_reversed_outcomes():
    """REQ-011: extract_1x2 findet den Yes-Preis ueber das Label, auch bei [No, Yes]."""
    from src.data_sources.polymarket_client import extract_1x2
    event = {"slug": "fifwc-bra-mar-2026-06-13", "title": "Brazil vs. Morocco",
             "markets": [
                 {"question": "Will Brazil win on 2026-06-13?",
                  "outcomes": '["No","Yes"]', "outcomePrices": '["0.45","0.55"]',
                  "conditionId": "c1", "volumeNum": 100},
                 {"question": "Will Morocco win on 2026-06-13?",
                  "outcomes": '["No","Yes"]', "outcomePrices": '["0.80","0.20"]',
                  "conditionId": "c2", "volumeNum": 100},
                 {"question": "Will Brazil vs. Morocco end in a draw?",
                  "outcomes": '["No","Yes"]', "outcomePrices": '["0.75","0.25"]',
                  "conditionId": "c3", "volumeNum": 100}]}
    res = extract_1x2(event)
    assert res is not None
    # Yes-Preise: Brazil 0.55 (index 1), Morocco 0.20, draw 0.25 -> Brazil klar vorne
    assert res["probs"]["team1_win"] > res["probs"]["team2_win"]
    assert res["raw"]["team1_win"] == 0.55 and res["raw"]["draw"] == 0.25


def test_bug010_canonical_team_and_matchers_none_safe():
    """BUG-010 (im Daily-Run entdeckt): None-Teamname darf nicht crashen und nicht falsch matchen."""
    from src import config
    from src.model.calibration import _team_eq
    from src.data_sources.odds_client import _team_match
    assert config.canonical_team(None) == ""        # kein AttributeError
    assert _team_eq(None, "Spain") is False          # leer matcht nichts (sonst "" in "spain")
    assert _team_eq("Spain", None) is False
    assert _team_match(None, "Brazil") is False
    assert _team_eq("Spain", "Spain") is True        # echte Treffer bleiben


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-q"]))
