# Generated by Quality Playbook v1.5.6 — https://github.com/andrewstellman/quality-playbook
# Author: Andrew Stellman · Date: 2026-06-14 · Project: wm-dashboard-fussball-wahrscheinlichkeit
"""Funktionale Tests — spezifikationsabgeleitete Sicherheitsnetz-Tests.

Gruppen:
  1. Spec-Requirements  — testbare Vertraege aus den Modul-Docstrings/Verhalten
  2. Fitness-Szenarien  — 1:1 zu quality/QUALITY.md
  3. Grenzen/Edge-Cases — defensive Muster der Kernmodule

Importmuster wie tests/test_model.py: Repo-Root auf sys.path, dann `from src...`.
Diese Tests pruefen das KORREKTE Verhalten (gruener Pfad). Bug-Demonstrationen fuer
die Kandidaten CB-1..CB-6 liegen als Regressionstests in Phase 3 (quality/test_regression.py).
"""
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


def approx(a, b, tol=1e-6):
    assert abs(a - b) < tol, f"{a} != {b}"


# ============================================================ 1. Spec-Requirements

def test_req001_simulate_normalizes_and_distributions_sum():
    """REQ-001: simulate liefert normierte 1X2 + konsistente Verteilungen (runs>=200)."""
    from src.model import monte_carlo
    mc = monte_carlo.simulate(1.5, 1.1, runs=4000, seed=3)
    p = mc["probs"]
    approx(p["team1_win"] + p["draw"] + p["team2_win"], 1.0, 1e-9)
    approx(sum(mc["total_goals_dist"]), 1.0, 0.01)
    approx(sum(mc["goals_team1_dist"]), 1.0, 0.01)
    approx(sum(sum(r) for r in mc["score_matrix"]), 1.0, 0.01)


def test_req001_uncertainty_band_present_and_ordered():
    """REQ-001/002: jedes Ausgangsband hat p05<=p95 und liegt in [0,1]."""
    from src.model import monte_carlo
    b = monte_carlo.simulate(1.6, 1.0, runs=6000, seed=5)["uncertainty"]
    for k in ("team1_win", "draw", "team2_win"):
        assert 0.0 <= b[k]["p05"] <= b[k]["p95"] <= 1.0, (k, b[k])


def test_req004_totals_half_lines_complementary():
    """REQ-004: bei .5-Linien gilt p_over + p_under == 1 (kein Push moeglich)."""
    from src.model import monte_carlo, value_betting
    mc = monte_carlo.simulate(1.4, 1.2, runs=4000, seed=9)
    td = mc["total_goals_dist"]
    for line in (1.5, 2.5, 3.5):
        floor = int(line)
        p_over = round(1.0 - sum(td[: floor + 1]), 4)
        p_under = round(1.0 - p_over, 4)
        approx(p_over + p_under, 1.0, 1e-9)


def test_req005_sigma_monotone_in_bandwidth_and_disagreement():
    """REQ-005: estimate_sigma steigt mit Bandbreite und Markt-Modell-Diskrepanz."""
    from src.model import value_betting as vb
    base = vb.estimate_sigma(0.05, 0.02)
    assert vb.estimate_sigma(0.25, 0.02) > base
    assert vb.estimate_sigma(0.05, 0.20) > base
    assert base >= vb.SIGMA_FLOOR


def test_req010_red_tier_suppresses_value():
    """REQ-010: rote Datenqualitaet unterdrueckt Value-Flags und nullt Einsaetze nicht-negativ."""
    from src.model import value_betting as vb
    value = {"rows": [{"stake_pct": 1.0, "stake_central": 1.0, "is_value": True}],
             "value_bets": [{"is_value": True}]}
    out = vb.apply_quality_gate(dict(value, rows=[dict(value["rows"][0])]),
                                {"tier": "red", "stake_multiplier": 0.0})
    assert out["value_bets"] == []
    assert out["rows"][0]["is_value"] is False
    assert out["data_quality_tier"] == "red"


def test_req010_green_tier_keeps_value_and_scales():
    from src.model import value_betting as vb
    value = {"rows": [{"stake_pct": 2.0, "stake_central": 2.0, "is_value": True}],
             "value_bets": [{"is_value": True}]}
    out = vb.apply_quality_gate(value, {"tier": "amber", "stake_multiplier": 0.5})
    assert out["rows"][0]["stake_pct"] == 1.0  # 2.0 * 0.5
    assert out["data_quality_tier"] == "amber"


def test_req012_calibration_leakage_filter():
    """REQ-012: nur Pre-Kickoff-Snapshots; timezone-korrekt."""
    import datetime as dt
    from src.model.calibration import _to_utc, _parse_kickoff
    k = _parse_kickoff("2026-06-13T01:00:00Z")
    assert _to_utc("2026-06-12T22:33:00+00:00") < k
    assert not (_to_utc("2026-06-13T02:00:00+00:00") < k)


# ============================================================ 2. Fitness-Szenarien

def test_fitness_devig_removes_overround():
    """QUALITY S1: Entviggen entfernt die Marge, Reihenfolge bleibt erhalten."""
    from src.data_sources.odds_client import _devig
    p = _devig({"home": 2.0, "draw": 3.4, "away": 4.2})
    approx(sum(p.values()), 1.0, 1e-9)
    assert p["home"] > p["draw"] > p["away"]


def test_fitness_shin_corrects_favorite_longshot():
    """QUALITY S2: Shin hebt Favorit, senkt Aussenseiter ggue. proportional."""
    from src.data_sources.odds_client import _devig, _devig_shin
    odds = {"home": 1.5, "draw": 4.5, "away": 8.0}
    prop, shin = _devig(odds), _devig_shin(odds)
    approx(sum(shin.values()), 1.0, 1e-6)
    assert shin["away"] < prop["away"] and shin["home"] > prop["home"]


def test_fitness_dixon_coles_raises_draws():
    """QUALITY S3: DC (rho<0) hebt Remis an, kontrolliert (wenige Prozentpunkte)."""
    from src.model import features
    _, pd0, _ = features.poisson_1x2(1.6, 1.0, rho=0.0)
    _, pdc, _ = features.poisson_1x2(1.6, 1.0, rho=-0.10)
    assert pdc > pd0 and 0.0 < (pdc - pd0) < 0.06


def test_fitness_whale_gate_caps_influence():
    """QUALITY S4: ein Extrem-Whale verschiebt den Blend um max. WHALE_SHIFT_CAP."""
    from src.model.ensemble import blend_probs
    agree = {"probs": {"team1_win": 0.30, "draw": 0.30, "team2_win": 0.40}}
    whale = {"probs": {"team1_win": 0.95, "draw": 0.03, "team2_win": 0.02},
             "n_wallets_scored": 10, "wallets": [{"confidence": 1.0}]}
    b = blend_probs(agree, dict(agree), whale, books=dict(agree))
    assert b["probs"]["team1_win"] <= 0.30 + 0.085
    approx(sum(b["probs"].values()), 1.0, 1e-6)


def test_fitness_portfolio_correlation_cap():
    """QUALITY S5: korrelierte Wetten im selben Spiel werden auf PER_MATCH_CAP gedeckelt."""
    from src.model.value_betting import portfolio
    bets = [{"slug": "g1", "ev": 0.10, "stake_pct": 1.5, "selection": "A"},
            {"slug": "g1", "ev": 0.08, "stake_pct": 1.5, "selection": "B"},
            {"slug": "g2", "ev": 0.05, "stake_pct": 1.0, "selection": "C"}]
    pf = portfolio(bets)
    g1 = sum(b["stake_pct_final"] for b in pf["plan"] if b["slug"] == "g1")
    assert g1 <= 2.0 + 1e-9 and pf["per_match_capped"] is True


def test_fitness_stake_capped_by_tier():
    """QUALITY S6: selbst bei riesigem Edge bleibt der Einsatz unter dem high-Tier-Cap."""
    from src.model import value_betting as vb
    r = vb._row("1X2", "Sieg A", 5.0, "X", 0.90, 0.90, band_width=0.50, n_books=20)
    assert r["risk"] == "high" and r["stake_pct"] <= 0.75 + 1e-9


def test_fitness_liquidity_gate_blocks_thin_markets():
    """QUALITY S7: unter MIN_BOOKS keine Value-Empfehlung, kein Einsatz."""
    from src.model import value_betting as vb
    r = vb._row("1X2", "Sieg A", 3.0, "X", 0.55, 0.52, band_width=0.05, n_books=2)
    assert r["is_value"] is False and r["stake_pct"] == 0.0


def test_fitness_mc_matches_analytic_dixon_coles():
    """QUALITY S8: importance-gewichtetes MC reproduziert die analytische DC-Verteilung."""
    from src.model import features, monte_carlo
    _, ad, _ = features.poisson_1x2(1.6, 1.0, rho=-0.10)
    mc = monte_carlo.simulate(1.6, 1.0, runs=40000, seed=11, rho=-0.10)
    assert abs(mc["probs"]["draw"] - ad) < 0.03


# ============================================================ 3. Grenzen/Edge-Cases

def test_edge_ensemble_renormalizes_when_source_missing():
    from src.model.ensemble import blend_probs
    from src.config import ENSEMBLE_WEIGHTS as W
    market = {"probs": {"team1_win": 0.5, "draw": 0.3, "team2_win": 0.2}}
    model = {"probs": {"team1_win": 0.4, "draw": 0.3, "team2_win": 0.3}}
    b = blend_probs(market, model, None)
    approx(sum(b["probs"].values()), 1.0, 1e-6)
    assert "whale" not in b["weights_used"]
    approx(b["weights_used"]["market"], W["market"] / (W["market"] + W["model"]), 1e-3)


def test_edge_ensemble_no_sources_returns_none():
    from src.model.ensemble import blend_probs
    b = blend_probs(None, None, None)
    assert b["probs"] is None and b["weights_used"] == {}


def test_edge_poisson_extreme_favorite_still_normalized():
    from src.model import features
    p1, pd, p2 = features.poisson_1x2(3.2, 0.3)
    approx(p1 + pd + p2, 1.0, 1e-9)
    assert p1 > p2


def test_edge_market_implied_roundtrip():
    from src.model import features
    p1, pd, p2 = features.poisson_1x2(1.8, 0.9)
    sol = features.market_implied_lambdas(p1, pd, p2)
    assert abs(sol["lambda1"] - 1.8) < 0.15 and abs(sol["lambda2"] - 0.9) < 0.15


def test_edge_brier_bounds():
    from src.model.calibration import brier
    approx(brier({"team1_win": 1.0, "draw": 0.0, "team2_win": 0.0}, "team1_win"), 0.0)
    approx(brier({"team1_win": 1.0, "draw": 0.0, "team2_win": 0.0}, "team2_win"), 2.0)


def test_edge_rps_ordinal_distance():
    from src.model.calibration import rps
    away = {"team1_win": 0.0, "draw": 0.0, "team2_win": 1.0}
    draw = {"team1_win": 0.0, "draw": 1.0, "team2_win": 0.0}
    assert rps(away, "team1_win") > rps(draw, "team1_win")


def test_edge_knockout_advancement_sums_to_one():
    from src.model.knockout import advancement_probs
    r = advancement_probs(1.3, 1.3, 0.40, 0.20, 0.40)
    approx(r["team1_advance"] + r["team2_advance"], 1.0, 1e-6)
    approx(r["team1_advance"], 0.5, 0.02)


def test_edge_data_quality_red_when_thin():
    """Duenne Lage (nur 1 Marktquelle, keine Live-Quoten, kein SB/Form) -> niedriger Score."""
    from src.model import data_quality
    match = {"model": {"elo": {"status": "estimated"}, "statsbomb_status": "unavailable",
                       "tournament_form": None},
             "market": {"probs": {"team1_win": 0.5, "draw": 0.3, "team2_win": 0.2}},
             "value": {"has_live_odds": False}}
    dq = data_quality.score_match(match)
    assert dq["tier"] in ("amber", "red")
    assert 0.0 <= dq["score"] <= 1.0
    assert dq["stake_multiplier"] in (0.0, 0.5, 1.0)


def test_edge_static_export_escapes_script_breakout():
    from src.pipeline.export_static import _inline_json
    s = _inline_json({"x": "evil</script><img src=x onerror=alert(1)>"})
    assert "</script>" not in s and "\\u003c" in s


def test_edge_model_version_stable_format():
    from src import config
    assert config.MODEL_VERSION.startswith("m-") and len(config.MODEL_VERSION) == 10


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_"):
            fn()
            print(f"OK  {name}")
    print("Alle funktionalen Tests bestanden.")
