#!/bin/bash
# Generated by Quality Playbook v1.5.6 — verification probes for spec-audit triage
# REQ-007 probe: do any two canonical team names collide by substring in the current field?
set -euo pipefail
python - <<'PY'
import sys; sys.path.insert(0, ".")
from src import config
names = sorted(set(config.canonical_team(k) for k in config.ELO_RATINGS.keys()))
coll = [(a, b) for a in names for b in names if a != b and a.lower() in b.lower()]
assert not coll, f"REQ-007 substring collision present: {coll}"
print("PROBE PASS: no canonical-name substring collision in the 48-team field (REQ-007 hardening, not a bug).")
PY
